=  Windup 2.x Maven Plugin

== Overview

Windup Maven plugin is created collaboratively on the Windup project.
This `windup-maven-plugin` repository takes the implementation of the plugin, this repository will contain the source for the official Maven plugin when the Windup 2.0 ships.

== Prerequisites

We recommend to use Maven version 3.3.3 or higher.

== Procedure to build the plugin 
    
* The first time, you must clone the windup-maven-plugin GitHub repository. 
+
----
git clone https://github.com/windup/windup-maven-plugin.git
----
    
* Navigate to the local windup-maven-plugin directory.
+
----
cd windup-maven-plugin
----

* Build the project.
+
----
mvn clean install
----

== Procedure to use the plugin

An example showing how to use the plugin can be found https://github.com/windup/windup-quickstarts/blob/master/maven-plugin-usage/pom.xml[here].

The Windup Maven Plugin configuration maps to the Windup execution options.
For the list and explanation, see https://access.redhat.com/documentation/en/red-hat-jboss-migration-toolkit/version-2.4/windup-user-guide/#command-line-arguments[Windup command line arguments documentation].

